name: cordada-cms

services:
  api:
    build: .
    command: yarn start
    environment:
      DATABASE_HOST: db
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - ./sqlite:/usr/src/app/sqlite
